### ISSUE TITLE
리눅스에서 파이어폭스를 열 때 에러가 나요.

### ISSUE THREAD

**Issue by kybin** [lazypic/init#1]
파이어폭스가 이미 열려있다면서.. 새로 띄울수가 없다네요. 

이거 해결책 아세요?

**Comment by khw7096** [comment]
리눅스 노트북에서 테스트 해보고 알려줄께용

**Comment by kybin** [comment]
전에 남아있던 아이스 위젤 때문인가봐요 이제 잘 돼요. ㅋㅋㅋ
